default_language_version:
    python: python3.6

repos:
-   repo: local
    hooks:
    -   id: check-added-large-files 
        name: Check added large files.
        entry: check-added-large-files 
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: end-of-file-fixer
        name: Fix end-of-file
        entry: end-of-file-fixer
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: trailing-whitespace
        name: Trailing whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: check-merge-conflict
        name: Check merge conflict
        entry: check-merge-conflict
        language: system
        types: [python]
# -   repo: local
#     hooks:
#     -   id: autoflake
#         name: Remove unused imports.
#         entry: autoflake -i --remove-all-unused-imports --ignore-init-module-imports --expand-star-imports -v
#         language: system
#         types: [python]
-   repo: local
    hooks:
    -   id: isort
        name: Check python imports.
        entry: isort --filter-files
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: yapf
        name: Auto format python code.
        entry: yapf -i -p -vv
        language: system
        types: [python]
-   repo: local
    hooks:
    -   id: flake8
        name: Check pep8.
        entry: flake8
        language: system
        types: [python]
